name: CI

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        node-version:
          - 20.19.0
          - 22
          - 24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run check
